### ISSUE TITLE
day constant typo

### ISSUE THREAD

**Issue by Pyrolistical** [RyanBayne/TwitchPress-Core-WordPress-Plugin#1]
https://github.com/RyanBayne/TwitchPress-Core-WordPress-Plugin/blob/7b6fdb408bbd784829a05b8562bf3becd75d3474/includes/libraries/bugnet/handlers/class.bugnet-handler-tracing.php#L30

https://stackoverflow.com/questions/608856/magic-numbers-vs-named-constants/608885#608885

**Comment by RyanBayne** [comment]
Excellent find and made the change. It will be released in TwitchPress 2.0 next month. 

Thanks
